---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: juju-chaos
  namespace: default
spec:
  engineState: 'active'
  chaosServiceAccount: litmus-admin
  experiments:
    - name: juju-remove-unit
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '30'

            - name: JUJU_MODEL_UUID
              value: ''

            - name: APPLICATION
              value: ''

            # Comma-separated unit IDs, e.g. "myapp/0,myapp/1"
            - name: UNIT_IDS
              value: ''
