---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: juju-chaos
  namespace: default
spec:
  engineState: 'active'
  chaosServiceAccount: litmus-admin
  experiments:
    - name: juju-remove-relation
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '30'

            - name: JUJU_MODEL_UUID
              value: ''

            - name: ENDPOINT1
              value: ''

            - name: ENDPOINT2
              value: ''
