---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: juju-chaos
  namespace: default
spec:
  engineState: 'active'
  chaosServiceAccount: litmus-admin
  experiments:
    - name: juju-integrate
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '30'

            - name: JUJU_MODEL_UUID
              value: ''

            # Format: "app1:endpoint1"
            - name: ENDPOINT1
              value: ''

            # Format: "app2:endpoint2"
            - name: ENDPOINT2
              value: ''
        probe:
          - name: check-app-active
            type: jujuAppProbe
            jujuAppProbe/inputs:
              appName: ""
              targetStatus: "active"
              comparator:
                type: string
                criteria: equal
                value: "active"
            mode: EOT
            runProperties:
              probeTimeout: 180s
              interval: 5s
              retry: 3
          - name: check-unit-active
            type: jujuUnitProbe
            jujuUnitProbe/inputs:
              unitName: ""
              targetStatus: "active"
              comparator:
                type: string
                criteria: equal
                value: "active"
            mode: EOT
            runProperties:
              probeTimeout: 180s
              interval: 5s
              retry: 3
          - name: check-pebble-service
            type: jujuPebbleProbe
            jujuPebbleProbe/inputs:
              unitName: ""
              serviceName: ""
              targetState: "active"
              comparator:
                type: string
                criteria: equal
                value: "active"
            mode: EOT
            runProperties:
              probeTimeout: 180s
              interval: 5s
              retry: 3
