---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2026-05-09T00:00:00Z
  name: juju-add-app
  version: 0.1.0
  annotations:
    categories: Juju
    vendor: Canonical
spec:
  displayName: Juju Add App
  categoryDescription: |
    This fault deploys a new Juju application (charm) to test integration behavior.
    - It helps to test how existing applications handle new deployments and relations.
  keywords:
    - Juju
  platforms:
    - Juju
  maintainers:
    - name: Canonical
      email: litmus@canonical.com
  chaosType: infra
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://juju.is/docs
  icon:
    - url:
      mediatype: ""
